const Auth = {
  // 登录的RSA公钥
  PUBLIC_KEY: 'MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCGqLO0UNC87/wD37ZXVhRBc/UQXHGXm+I6uimWhJ7EViq5PfXXSTD0nibVnqfXsPGVlYzrwl5pffgQOyzDgxAOutADMbmpk3rAISGDslwQJ95wQRKOyedq/ezwaL68bO78qvHC9R+WA9tPivlSA9b9bui9BXHYPBUhk0/voGuvCQIDAQAB',
  // 加密方式
  ENCRYPT_TYPE: 'RSA',
  CLIENT_CODE: 'OA_CUSTOMER',
  LOGIN_TYPE: 'OA_EMAIL',
  LOGIN_AUTH: 'OA_V2',
  IDENTITY_TYPE: 'INNER',
  IGNORE_ENCRYPT: false,
};

export default Auth;
