/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AnimalImg: typeof import('./components/animal-img.vue')['default']
    Icon: typeof import('./components/icon.vue')['default']
    RealTimeVideo: typeof import('./components/RealTimeVideo/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StcVideo: typeof import('./components/stc-video.vue')['default']
  }
}
